In [31]:
# Numpyをインポート
import numpy as np

# AとBの行列を格納する多次元配列
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# 行列の積の計算をするコード
total = np.dot(A, B)

# 行列の積の計算結果を表示
print("行列の積の計算結果は以下の通りとなります。")
print(total)
# 行列の要素の最大値
print(f"最大値は{total.max()}です。")


行列の積の計算結果は以下の通りとなります。
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値は47です。
